# Generated by Django 2.2.2 on 2019-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', help_text='Enter the language the book is written in.', max_length=100),
        ),
    ]
